// Generated by CoffeeScript 1.9.1
(function() {
  var a, b, d, fi, food, i, len, ref;

  a = 1;

  b = function(x) {
    return x * x;
  };

  fi = function(a, b) {
    if (b == null) {
      b = '123';
    }
    return "this is a " + a + " and that is " + b;
  };

  ref = ['a', 'b', 1];
  for (i = 0, len = ref.length; i < len; i++) {
    food = ref[i];
    if (food !== 1) {
      eat(food);
    }
  }

  d = 3;

}).call(this);
